# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1076, 564)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.banking_tree_btn = QtWidgets.QPushButton(self.frame)
        self.banking_tree_btn.setObjectName("banking_tree_btn")
        self.horizontalLayout.addWidget(self.banking_tree_btn)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame)
        self.treeWidget = QtWidgets.QTreeView(Form)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.banking_tree_btn.setText(_translate("Form", "banking"))
        self.pushButton.setText(_translate("Form", "designing"))
        self.pushButton_3.setText(_translate("Form", "save"))
        # self.treeWidget.headerItem().setText(0, _translate("Form", "Bank Names"))
        # self.treeWidget.headerItem().setText(1, _translate("Form", "Fmv"))
        # self.treeWidget.headerItem().setText(2, _translate("Form", "Charges"))
        # self.treeWidget.headerItem().setText(3, _translate("Form", "Initial Payment"))
        # self.treeWidget.headerItem().setText(4, _translate("Form", "Final Payment"))
        # self.treeWidget.headerItem().setText(5, _translate("Form", "Dew Baalance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
