# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_baccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 512)
        Form.setMinimumSize(QtCore.QSize(550, 512))
        Form.setMaximumSize(QtCore.QSize(550, 512))
        Form.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
"\n"
"border:2px solid ;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.stackedWidget.setStyleSheet("border:0px")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setStyleSheet("border-radius:9px;\n"
"background-color:transparent;\n"
"border:2px solid grey;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addstatement = QtWidgets.QPushButton(self.frame)
        self.addstatement.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.addstatement.setStyleSheet("border:0px;")
        self.addstatement.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/math-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addstatement.setIcon(icon)
        self.addstatement.setIconSize(QtCore.QSize(40, 40))
        self.addstatement.setObjectName("addstatement")
        self.verticalLayout_4.addWidget(self.frame)
        self.groupBox_18 = QtWidgets.QGroupBox(self.page)
        self.groupBox_18.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_18.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_2.setContentsMargins(12, 12, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_30 = QtWidgets.QFrame(self.groupBox_18)
        self.frame_30.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_30.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_30.setStyleSheet("background-color: transparent;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_32.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_32.setSpacing(10)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_98 = QtWidgets.QLabel(self.frame_30)
        self.label_98.setMinimumSize(QtCore.QSize(0, 40))
        self.label_98.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_32.addWidget(self.label_98)
        self.label_99 = QtWidgets.QLabel(self.frame_30)
        self.label_99.setMinimumSize(QtCore.QSize(0, 40))
        self.label_99.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_32.addWidget(self.label_99)
        self.gridLayout_2.addWidget(self.frame_30, 0, 0, 2, 1, QtCore.Qt.AlignTop)
        self.frame_31 = QtWidgets.QFrame(self.groupBox_18)
        self.frame_31.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_31.setStyleSheet("background-color: transparent")
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_2.setContentsMargins(-1, 12, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dclient_name_3 = QtWidgets.QLineEdit(self.frame_31)
        self.dclient_name_3.setMinimumSize(QtCore.QSize(0, 40))
        self.dclient_name_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dclient_name_3.setFont(font)
        self.dclient_name_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dclient_name_3.setObjectName("dclient_name_3")
        self.verticalLayout_2.addWidget(self.dclient_name_3)
        self.catageory_3 = QtWidgets.QLineEdit(self.frame_31)
        self.catageory_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catageory_3.setFont(font)
        self.catageory_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.catageory_3.setObjectName("catageory_3")
        self.verticalLayout_2.addWidget(self.catageory_3)
        self.gridLayout_2.addWidget(self.frame_31, 0, 1, 2, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.page)
        self.groupBox_19.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_19.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_3.setContentsMargins(12, 12, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_33 = QtWidgets.QFrame(self.groupBox_19)
        self.frame_33.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_33.setStyleSheet("background-color: transparent")
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_3.setContentsMargins(-1, 12, -1, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_33)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_104 = QtWidgets.QLabel(self.frame_3)
        self.label_104.setMinimumSize(QtCore.QSize(0, 40))
        self.label_104.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_104.setFont(font)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_104)
        self.label_102 = QtWidgets.QLabel(self.frame_3)
        self.label_102.setMinimumSize(QtCore.QSize(0, 40))
        self.label_102.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_102.setFont(font)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_102)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.gridLayout_3.addWidget(self.frame_33, 0, 1, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.groupBox_19)
        self.frame_32.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_32.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_32.setStyleSheet("background-color: transparent;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_33.setContentsMargins(0, 25, 0, 12)
        self.verticalLayout_33.setSpacing(10)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_100 = QtWidgets.QLabel(self.frame_32)
        self.label_100.setMinimumSize(QtCore.QSize(0, 40))
        self.label_100.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_100.setFont(font)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_33.addWidget(self.label_100)
        self.label_101 = QtWidgets.QLabel(self.frame_32)
        self.label_101.setMinimumSize(QtCore.QSize(0, 40))
        self.label_101.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_101.setFont(font)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_33.addWidget(self.label_101)
        self.gridLayout_3.addWidget(self.frame_32, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_19)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setStyleSheet("background-color:transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_2.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_18.setTitle(_translate("Form", "Bank Information"))
        self.label_98.setText(_translate("Form", "Bank Name"))
        self.label_99.setText(_translate("Form", "Branch"))
        self.groupBox_19.setTitle(_translate("Form", "Formula For Above Bank"))
        self.label_104.setText(_translate("Form", "FMV * "))
        self.label_102.setText(_translate("Form", "FMV * "))
        self.label_100.setText(_translate("Form", "For Less Than 50 L <"))
        self.label_101.setText(_translate("Form", "For Less Than 50 L >"))
        self.pushButton.setText(_translate("Form", "Ok"))
        self.pushButton_2.setText(_translate("Form", "Cancle"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
