# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dtransactions.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(506, 350)
        Form.setMinimumSize(QtCore.QSize(500, 350))
        Form.setMaximumSize(QtCore.QSize(506, 350))
        Form.setStyleSheet("\n"
"QWidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
"\n"
"border:2px solid;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background:transparent;\n"
"border:0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(12, 0, 12, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("\n"
"background:white;\n"
"border-radius: 3px;\n"
"border:1px solid grey;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background:transparent")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("\n"
"background:white;\n"
"border-radius: 3px;\n"
"border:1px solid grey;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"background:white;\n"
"border-radius: 3px;\n"
"border:1px solid grey;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.bank_name = QtWidgets.QComboBox(self.frame)
        self.bank_name.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name.setFont(font)
        self.bank_name.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name.setObjectName("bank_name")
        self.gridLayout.addWidget(self.bank_name, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.bank_name_2 = QtWidgets.QComboBox(self.frame)
        self.bank_name_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name_2.setFont(font)
        self.bank_name_2.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name_2.setObjectName("bank_name_2")
        self.gridLayout.addWidget(self.bank_name_2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setStyleSheet("background-color:transparent; border:0")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.login_btn_2.setMinimumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_btn_2.setFont(font)
        self.login_btn_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.156682 rgba(0, 155, 255, 255), stop:1 rgba(175, 255, 247, 255));\n"
"border-radius:9px;\n"
"border:2px solid;}\n"
"\n"
"QPushButton:hover{\n"
"background-color:  rgb(152, 255, 124);\n"
"}")
        self.login_btn_2.setAutoDefault(True)
        self.login_btn_2.setObjectName("login_btn_2")
        self.horizontalLayout.addWidget(self.login_btn_2)
        self.login_btn_3 = QtWidgets.QPushButton(self.frame_2)
        self.login_btn_3.setMinimumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_btn_3.setFont(font)
        self.login_btn_3.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.156682 rgba(0, 155, 255, 255), stop:1 rgba(175, 255, 247, 255));\n"
"border-radius:9px;\n"
"border:2px solid;}\n"
"\n"
"QPushButton:hover{\n"
"background-color:  rgb(152, 255, 124);\n"
"}")
        self.login_btn_3.setAutoDefault(True)
        self.login_btn_3.setObjectName("login_btn_3")
        self.horizontalLayout.addWidget(self.login_btn_3)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Received Amount"))
        self.label_4.setText(_translate("Form", "Closing Balance"))
        self.label.setText(_translate("Form", "Prev Dew Balance"))
        self.label_3.setText(_translate("Form", "Categeory"))
        self.label_5.setText(_translate("Form", "Client Name"))
        self.login_btn_2.setText(_translate("Form", "Save"))
        self.login_btn_3.setText(_translate("Form", "Cancle"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
