# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dentry.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1058, 700)
        Form.setMinimumSize(QtCore.QSize(1058, 700))
        Form.setMaximumSize(QtCore.QSize(1058, 700))
        Form.setStyleSheet("border:4px solid grey;\n"
"border-radius:5px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(12, 25, 12, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color:transparent;\n"
"border-radius:9px;\n"
"border:2px solid grey;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.find = QtWidgets.QPushButton(self.frame)
        self.find.setGeometry(QtCore.QRect(20, 20, 48, 44))
        self.find.setStyleSheet("border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;\n"
"border-radius: 0px;")
        self.find.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Actions-document-preview-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find.setIcon(icon)
        self.find.setIconSize(QtCore.QSize(40, 40))
        self.find.setObjectName("find")
        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setGeometry(QtCore.QRect(80, 20, 48, 44))
        self.save.setStyleSheet("border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;\n"
"border-radius: 0px;")
        self.save.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(40, 40))
        self.save.setObjectName("save")
        self.add = QtWidgets.QPushButton(self.frame)
        self.add.setGeometry(QtCore.QRect(140, 20, 48, 44))
        self.add.setStyleSheet("border-radius: 0px;border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;")
        self.add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/math-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon2)
        self.add.setIconSize(QtCore.QSize(40, 40))
        self.add.setObjectName("add")
        self.previous = QtWidgets.QPushButton(self.frame)
        self.previous.setGeometry(QtCore.QRect(200, 20, 48, 44))
        self.previous.setStyleSheet("border-radius: 0px;border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;")
        self.previous.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Actions-go-previous-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous.setIcon(icon3)
        self.previous.setIconSize(QtCore.QSize(40, 40))
        self.previous.setObjectName("previous")
        self.next = QtWidgets.QPushButton(self.frame)
        self.next.setGeometry(QtCore.QRect(260, 20, 48, 44))
        self.next.setStyleSheet("border-radius: 0px;border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;")
        self.next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Actions-go-next-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon4)
        self.next.setIconSize(QtCore.QSize(40, 40))
        self.next.setObjectName("next")
        self.banking_sector_entry = QtWidgets.QPushButton(self.frame)
        self.banking_sector_entry.setGeometry(QtCore.QRect(320, 20, 48, 44))
        self.banking_sector_entry.setStyleSheet("border-radius: 0px;border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;")
        self.banking_sector_entry.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/Letter-B-lg-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.banking_sector_entry.setIcon(icon5)
        self.banking_sector_entry.setIconSize(QtCore.QSize(40, 40))
        self.banking_sector_entry.setObjectName("banking_sector_entry")
        self.setting = QtWidgets.QPushButton(self.frame)
        self.setting.setGeometry(QtCore.QRect(380, 20, 48, 44))
        self.setting.setStyleSheet("border-radius: 0px;border-right: 0px;\n"
"border-left: 0px;\n"
"border-top: 0px;")
        self.setting.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting.setIcon(icon6)
        self.setting.setIconSize(QtCore.QSize(40, 40))
        self.setting.setObjectName("setting")
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"background-color:transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(-1, 30, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_78 = QtWidgets.QLabel(self.groupBox)
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("background-color:transparent;\n"
"border: 0px;")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_2.addWidget(self.label_78)
        self.catageory_2 = QtWidgets.QLineEdit(self.groupBox)
        self.catageory_2.setMinimumSize(QtCore.QSize(0, 40))
        self.catageory_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catageory_2.setFont(font)
        self.catageory_2.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.catageory_2.setObjectName("catageory_2")
        self.horizontalLayout_2.addWidget(self.catageory_2)
        self.label_80 = QtWidgets.QLabel(self.groupBox)
        self.label_80.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("background-color:transparent;border: 0px;")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_2.addWidget(self.label_80)
        self.client_name = QtWidgets.QLineEdit(self.groupBox)
        self.client_name.setMinimumSize(QtCore.QSize(0, 40))
        self.client_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client_name.setFont(font)
        self.client_name.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.client_name.setObjectName("client_name")
        self.horizontalLayout_2.addWidget(self.client_name)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background-color:transparent; border: 0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_14 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_14.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"background-color:transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_25.setContentsMargins(0, 12, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_22 = QtWidgets.QFrame(self.groupBox_14)
        self.frame_22.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_22.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_22.setStyleSheet("background-color: transparent;border: 0px;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_72 = QtWidgets.QLabel(self.frame_22)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_24.addWidget(self.label_72)
        self.label_73 = QtWidgets.QLabel(self.frame_22)
        self.label_73.setMinimumSize(QtCore.QSize(0, 40))
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_24.addWidget(self.label_73)
        self.label_74 = QtWidgets.QLabel(self.frame_22)
        self.label_74.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_74.setFont(font)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_24.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.frame_22)
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_24.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(self.frame_22)
        self.label_76.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_76.setFont(font)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_24.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(self.frame_22)
        self.label_77.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_77.setFont(font)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_24.addWidget(self.label_77)
        self.horizontalLayout_25.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.groupBox_14)
        self.frame_23.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_23.setStyleSheet("background-color: transparent; border: 0px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_25.setContentsMargins(0, 0, 12, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.dfile_code = QtWidgets.QLineEdit(self.frame_23)
        self.dfile_code.setMinimumSize(QtCore.QSize(0, 40))
        self.dfile_code.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dfile_code.setFont(font)
        self.dfile_code.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dfile_code.setText("")
        self.dfile_code.setObjectName("dfile_code")
        self.verticalLayout_25.addWidget(self.dfile_code)
        self.file_type = QtWidgets.QLineEdit(self.frame_23)
        self.file_type.setMinimumSize(QtCore.QSize(0, 40))
        self.file_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_type.setFont(font)
        self.file_type.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.file_type.setObjectName("file_type")
        self.verticalLayout_25.addWidget(self.file_type)
        self.email_address = QtWidgets.QLineEdit(self.frame_23)
        self.email_address.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_address.setFont(font)
        self.email_address.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.email_address.setObjectName("email_address")
        self.verticalLayout_25.addWidget(self.email_address)
        self.dcontact_no = QtWidgets.QLineEdit(self.frame_23)
        self.dcontact_no.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dcontact_no.setFont(font)
        self.dcontact_no.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dcontact_no.setObjectName("dcontact_no")
        self.verticalLayout_25.addWidget(self.dcontact_no)
        self.dcc_person = QtWidgets.QLineEdit(self.frame_23)
        self.dcc_person.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dcc_person.setFont(font)
        self.dcc_person.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dcc_person.setObjectName("dcc_person")
        self.verticalLayout_25.addWidget(self.dcc_person)
        self.daddress = QtWidgets.QLineEdit(self.frame_23)
        self.daddress.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.daddress.setFont(font)
        self.daddress.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.daddress.setText("")
        self.daddress.setObjectName("daddress")
        self.verticalLayout_25.addWidget(self.daddress)
        self.horizontalLayout_25.addWidget(self.frame_23)
        self.horizontalLayout.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_15.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_15.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"background-color:transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_26.setContentsMargins(0, 12, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_24 = QtWidgets.QFrame(self.groupBox_15)
        self.frame_24.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_24.setMaximumSize(QtCore.QSize(685, 16777215))
        self.frame_24.setStyleSheet("background-color: transparent;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_26.setContentsMargins(12, 20, 12, 12)
        self.verticalLayout_26.setSpacing(12)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_79 = QtWidgets.QLabel(self.frame_24)
        self.label_79.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_26.addWidget(self.label_79)
        self.label_82 = QtWidgets.QLabel(self.frame_24)
        self.label_82.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_26.addWidget(self.label_82)
        self.label_96 = QtWidgets.QLabel(self.frame_24)
        self.label_96.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_96.setFont(font)
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_26.addWidget(self.label_96)
        self.label_83 = QtWidgets.QLabel(self.frame_24)
        self.label_83.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_83.setFont(font)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_26.addWidget(self.label_83)
        self.label_84 = QtWidgets.QLabel(self.frame_24)
        self.label_84.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_84.setFont(font)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_26.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(self.frame_24)
        self.label_85.setMinimumSize(QtCore.QSize(0, 40))
        self.label_85.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_85.setFont(font)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_26.addWidget(self.label_85)
        self.label_86 = QtWidgets.QLabel(self.frame_24)
        self.label_86.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_86.setFont(font)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_26.addWidget(self.label_86)
        self.horizontalLayout_26.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.groupBox_15)
        self.frame_25.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_25.setStyleSheet("background-color: transparent;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_27.setContentsMargins(0, 20, -1, 0)
        self.verticalLayout_27.setSpacing(12)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_8 = QtWidgets.QFrame(self.frame_25)
        self.frame_8.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.dd_dd = QtWidgets.QLineEdit(self.frame_8)
        self.dd_dd.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_dd.setMaximumSize(QtCore.QSize(743, 1176))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_dd.setFont(font)
        self.dd_dd.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_dd.setObjectName("dd_dd")
        self.horizontalLayout_21.addWidget(self.dd_dd)
        self.dd_mm = QtWidgets.QLineEdit(self.frame_8)
        self.dd_mm.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_mm.setMaximumSize(QtCore.QSize(919, 624))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_mm.setFont(font)
        self.dd_mm.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_mm.setObjectName("dd_mm")
        self.horizontalLayout_21.addWidget(self.dd_mm)
        self.dd_yy = QtWidgets.QLineEdit(self.frame_8)
        self.dd_yy.setMinimumSize(QtCore.QSize(160, 40))
        self.dd_yy.setMaximumSize(QtCore.QSize(627, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_yy.setFont(font)
        self.dd_yy.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_yy.setObjectName("dd_yy")
        self.horizontalLayout_21.addWidget(self.dd_yy)
        self.verticalLayout_27.addWidget(self.frame_8)
        self.frame_14 = QtWidgets.QFrame(self.frame_25)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.browse_edit = QtWidgets.QLineEdit(self.frame_14)
        self.browse_edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_edit.setFont(font)
        self.browse_edit.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.browse_edit.setObjectName("browse_edit")
        self.horizontalLayout_5.addWidget(self.browse_edit)
        self.browse_btn = QtWidgets.QPushButton(self.frame_14)
        self.browse_btn.setMinimumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.browse_btn.setFont(font)
        self.browse_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"border:1px solid grey;\n"
"border-radius:3px;\n"
"}\n"
"")
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_5.addWidget(self.browse_btn)
        self.verticalLayout_27.addWidget(self.frame_14)
        self.dfmv = QtWidgets.QLineEdit(self.frame_25)
        self.dfmv.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dfmv.setFont(font)
        self.dfmv.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dfmv.setObjectName("dfmv")
        self.verticalLayout_27.addWidget(self.dfmv)
        self.dcharges = QtWidgets.QLineEdit(self.frame_25)
        self.dcharges.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dcharges.setFont(font)
        self.dcharges.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dcharges.setObjectName("dcharges")
        self.verticalLayout_27.addWidget(self.dcharges)
        self.dinitial_payment = QtWidgets.QLineEdit(self.frame_25)
        self.dinitial_payment.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dinitial_payment.setFont(font)
        self.dinitial_payment.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dinitial_payment.setObjectName("dinitial_payment")
        self.verticalLayout_27.addWidget(self.dinitial_payment)
        self.dfinal_payment = QtWidgets.QLineEdit(self.frame_25)
        self.dfinal_payment.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dfinal_payment.setFont(font)
        self.dfinal_payment.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dfinal_payment.setObjectName("dfinal_payment")
        self.verticalLayout_27.addWidget(self.dfinal_payment)
        self.ddew_balance = QtWidgets.QLineEdit(self.frame_25)
        self.ddew_balance.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ddew_balance.setFont(font)
        self.ddew_balance.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.ddew_balance.setObjectName("ddew_balance")
        self.verticalLayout_27.addWidget(self.ddew_balance)
        self.frame_15 = QtWidgets.QFrame(self.frame_25)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setContentsMargins(0, 0, 100, 0)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_27.addWidget(self.frame_15)
        self.horizontalLayout_26.addWidget(self.frame_25, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.groupBox_15)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color:transparent;border: 0px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dcalcle_btn = QtWidgets.QPushButton(self.frame_3)
        self.dcalcle_btn.setMinimumSize(QtCore.QSize(70, 40))
        self.dcalcle_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.dcalcle_btn.setFont(font)
        self.dcalcle_btn.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.dcalcle_btn.setObjectName("dcalcle_btn")
        self.horizontalLayout_3.addWidget(self.dcalcle_btn)
        self.dexit_btn = QtWidgets.QPushButton(self.frame_3)
        self.dexit_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.dexit_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.dexit_btn.setFont(font)
        self.dexit_btn.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.dexit_btn.setObjectName("dexit_btn")
        self.horizontalLayout_3.addWidget(self.dexit_btn)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Designing Information"))
        self.label_78.setText(_translate("Form", "Catageory"))
        self.label_80.setText(_translate("Form", "Client Name"))
        self.groupBox_14.setTitle(_translate("Form", "General Information"))
        self.label_72.setText(_translate("Form", "File Code"))
        self.label_73.setText(_translate("Form", "File Type"))
        self.label_74.setText(_translate("Form", "Email Address"))
        self.label_75.setText(_translate("Form", "Contact No"))
        self.label_76.setText(_translate("Form", "CC Person"))
        self.label_77.setText(_translate("Form", "Address"))
        self.groupBox_15.setTitle(_translate("Form", "Payment Informations"))
        self.label_79.setText(_translate("Form", "Date"))
        self.label_82.setText(_translate("Form", "Documents"))
        self.label_96.setText(_translate("Form", "fmv"))
        self.label_83.setText(_translate("Form", "Charges"))
        self.label_84.setText(_translate("Form", "Initial Payment"))
        self.label_85.setText(_translate("Form", "Final Payment"))
        self.label_86.setText(_translate("Form", "Dew Balance"))
        self.dd_dd.setPlaceholderText(_translate("Form", "DD"))
        self.dd_mm.setPlaceholderText(_translate("Form", "MM"))
        self.dd_yy.setPlaceholderText(_translate("Form", "YYYY"))
        self.browse_btn.setText(_translate("Form", "Browse"))
        self.dcalcle_btn.setText(_translate("Form", "Ok"))
        self.dexit_btn.setText(_translate("Form", "Cancle"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
