# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ladger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1076, 810)
        Form.setStyleSheet("    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
"border:2px solid;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background:transparent;\n"
"border:0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.bank_name = QtWidgets.QComboBox(self.frame)
        self.bank_name.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name.setFont(font)
        self.bank_name.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name.setCurrentText("")
        self.bank_name.setObjectName("bank_name")
        self.gridLayout.addWidget(self.bank_name, 1, 2, 1, 1)
        self.bank_name_4 = QtWidgets.QComboBox(self.frame)
        self.bank_name_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name_4.setFont(font)
        self.bank_name_4.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name_4.setCurrentText("")
        self.bank_name_4.setObjectName("bank_name_4")
        self.gridLayout.addWidget(self.bank_name_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 4, 1, 1)
        self.bank_name_2 = QtWidgets.QComboBox(self.frame)
        self.bank_name_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name_2.setFont(font)
        self.bank_name_2.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name_2.setObjectName("bank_name_2")
        self.gridLayout.addWidget(self.bank_name_2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom:0px;\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setStyleSheet("background:white;\n"
"border-top:1px solid;\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Export"))
        self.label.setText(_translate("Form", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Particulars"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cradit Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Debit Aamount"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Balance Amount"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
