# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_statementform.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 545)
        Form.setMinimumSize(QtCore.QSize(560, 545))
        Form.setMaximumSize(QtCore.QSize(560, 600))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
"border:2px solid;")
        Form.setWindowFilePath("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.bankpage = QtWidgets.QWidget()
        self.bankpage.setObjectName("bankpage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bankpage)
        self.verticalLayout.setContentsMargins(12, 12, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.bankpage)
        self.frame.setStyleSheet("background-color:transparent;\n"
"background-color:transparent;\n"
"border: 2px solid grey;\n"
"border-radius: 9px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.savestatement = QtWidgets.QPushButton(self.frame)
        self.savestatement.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"")
        self.savestatement.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savestatement.setIcon(icon)
        self.savestatement.setIconSize(QtCore.QSize(40, 40))
        self.savestatement.setObjectName("savestatement")
        self.horizontalLayout_5.addWidget(self.savestatement)
        self.addstatement = QtWidgets.QPushButton(self.frame)
        self.addstatement.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"")
        self.addstatement.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/math-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addstatement.setIcon(icon1)
        self.addstatement.setIconSize(QtCore.QSize(40, 40))
        self.addstatement.setObjectName("addstatement")
        self.horizontalLayout_5.addWidget(self.addstatement)
        self.addstatement_2 = QtWidgets.QPushButton(self.frame)
        self.addstatement_2.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"")
        self.addstatement_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Letter-D-lg-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addstatement_2.setIcon(icon2)
        self.addstatement_2.setIconSize(QtCore.QSize(40, 40))
        self.addstatement_2.setObjectName("addstatement_2")
        self.horizontalLayout_5.addWidget(self.addstatement_2)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.groupBox_18 = QtWidgets.QGroupBox(self.bankpage)
        self.groupBox_18.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_18.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_2.setContentsMargins(12, 12, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_30 = QtWidgets.QFrame(self.groupBox_18)
        self.frame_30.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_30.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_30.setStyleSheet("background-color: transparent;border:0px;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_32.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_32.setSpacing(10)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_98 = QtWidgets.QLabel(self.frame_30)
        self.label_98.setMinimumSize(QtCore.QSize(0, 40))
        self.label_98.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_32.addWidget(self.label_98)
        self.label_99 = QtWidgets.QLabel(self.frame_30)
        self.label_99.setMinimumSize(QtCore.QSize(0, 40))
        self.label_99.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_32.addWidget(self.label_99)
        self.label_100 = QtWidgets.QLabel(self.frame_30)
        self.label_100.setMinimumSize(QtCore.QSize(0, 40))
        self.label_100.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_100.setFont(font)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_32.addWidget(self.label_100)
        self.label_101 = QtWidgets.QLabel(self.frame_30)
        self.label_101.setMinimumSize(QtCore.QSize(0, 40))
        self.label_101.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_101.setFont(font)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_32.addWidget(self.label_101)
        self.label_102 = QtWidgets.QLabel(self.frame_30)
        self.label_102.setMinimumSize(QtCore.QSize(0, 40))
        self.label_102.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_102.setFont(font)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_32.addWidget(self.label_102)
        self.gridLayout_2.addWidget(self.frame_30, 0, 0, 2, 1)
        self.frame_31 = QtWidgets.QFrame(self.groupBox_18)
        self.frame_31.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_31.setStyleSheet("background-color: transparent;border:0px;")
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dclient_name_3 = QtWidgets.QLineEdit(self.frame_31)
        self.dclient_name_3.setMinimumSize(QtCore.QSize(0, 40))
        self.dclient_name_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dclient_name_3.setFont(font)
        self.dclient_name_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dclient_name_3.setObjectName("dclient_name_3")
        self.verticalLayout_2.addWidget(self.dclient_name_3)
        self.catageory_3 = QtWidgets.QLineEdit(self.frame_31)
        self.catageory_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catageory_3.setFont(font)
        self.catageory_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.catageory_3.setObjectName("catageory_3")
        self.verticalLayout_2.addWidget(self.catageory_3)
        self.daddress_3 = QtWidgets.QLineEdit(self.frame_31)
        self.daddress_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.daddress_3.setFont(font)
        self.daddress_3.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.daddress_3.setText("")
        self.daddress_3.setObjectName("daddress_3")
        self.verticalLayout_2.addWidget(self.daddress_3)
        self.frame_12 = QtWidgets.QFrame(self.frame_31)
        self.frame_12.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.dd_dd_5 = QtWidgets.QLineEdit(self.frame_12)
        self.dd_dd_5.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_dd_5.setMaximumSize(QtCore.QSize(743, 1176))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_dd_5.setFont(font)
        self.dd_dd_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_dd_5.setObjectName("dd_dd_5")
        self.horizontalLayout_25.addWidget(self.dd_dd_5)
        self.dd_mm_5 = QtWidgets.QLineEdit(self.frame_12)
        self.dd_mm_5.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_mm_5.setMaximumSize(QtCore.QSize(919, 624))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_mm_5.setFont(font)
        self.dd_mm_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_mm_5.setObjectName("dd_mm_5")
        self.horizontalLayout_25.addWidget(self.dd_mm_5)
        self.dd_yy_5 = QtWidgets.QLineEdit(self.frame_12)
        self.dd_yy_5.setMinimumSize(QtCore.QSize(180, 40))
        self.dd_yy_5.setMaximumSize(QtCore.QSize(627, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_yy_5.setFont(font)
        self.dd_yy_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_yy_5.setObjectName("dd_yy_5")
        self.horizontalLayout_25.addWidget(self.dd_yy_5)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_14 = QtWidgets.QFrame(self.frame_31)
        self.frame_14.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.dd_dd_7 = QtWidgets.QLineEdit(self.frame_14)
        self.dd_dd_7.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_dd_7.setMaximumSize(QtCore.QSize(743, 1176))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_dd_7.setFont(font)
        self.dd_dd_7.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_dd_7.setObjectName("dd_dd_7")
        self.horizontalLayout_27.addWidget(self.dd_dd_7)
        self.dd_mm_7 = QtWidgets.QLineEdit(self.frame_14)
        self.dd_mm_7.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_mm_7.setMaximumSize(QtCore.QSize(919, 624))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_mm_7.setFont(font)
        self.dd_mm_7.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_mm_7.setObjectName("dd_mm_7")
        self.horizontalLayout_27.addWidget(self.dd_mm_7)
        self.dd_yy_7 = QtWidgets.QLineEdit(self.frame_14)
        self.dd_yy_7.setMinimumSize(QtCore.QSize(180, 40))
        self.dd_yy_7.setMaximumSize(QtCore.QSize(627, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_yy_7.setFont(font)
        self.dd_yy_7.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_yy_7.setObjectName("dd_yy_7")
        self.horizontalLayout_27.addWidget(self.dd_yy_7)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_31)
        self.frame_13.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_2.addWidget(self.frame_13)
        self.gridLayout_2.addWidget(self.frame_31, 0, 1, 2, 1)
        self.verticalLayout.addWidget(self.groupBox_18)
        self.frame_2 = QtWidgets.QFrame(self.bankpage)
        self.frame_2.setStyleSheet("background-color:transparent;\n"
"border:0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_2.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.bankpage)
        self.designpage = QtWidgets.QWidget()
        self.designpage.setObjectName("designpage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.designpage)
        self.verticalLayout_6.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.designpage)
        self.frame_5.setStyleSheet("background-color:transparent;\n"
"border: 2px solid grey;\n"
"border-radius: 9px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(12, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignLeft)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setStyleSheet("border-top: 0px;\n"
"border-left:0px;\n"
"border-right:0px;\n"
"border-radius: 0px;\n"
"\n"
"")
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Letter-B-lg-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.verticalLayout_6.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.groupBox_20 = QtWidgets.QGroupBox(self.designpage)
        self.groupBox_20.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_20.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_20.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.8em;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 40px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_4.setContentsMargins(-1, 12, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_34 = QtWidgets.QFrame(self.groupBox_20)
        self.frame_34.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_34.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_34.setStyleSheet("background-color: transparent;border:0px;")
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_34.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_34.setSpacing(10)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_108 = QtWidgets.QLabel(self.frame_34)
        self.label_108.setMinimumSize(QtCore.QSize(0, 40))
        self.label_108.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_108.setFont(font)
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName("label_108")
        self.verticalLayout_34.addWidget(self.label_108)
        self.label_109 = QtWidgets.QLabel(self.frame_34)
        self.label_109.setMinimumSize(QtCore.QSize(0, 40))
        self.label_109.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_109.setFont(font)
        self.label_109.setAlignment(QtCore.Qt.AlignCenter)
        self.label_109.setObjectName("label_109")
        self.verticalLayout_34.addWidget(self.label_109)
        self.label_110 = QtWidgets.QLabel(self.frame_34)
        self.label_110.setMinimumSize(QtCore.QSize(0, 40))
        self.label_110.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_110.setFont(font)
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName("label_110")
        self.verticalLayout_34.addWidget(self.label_110)
        self.label_111 = QtWidgets.QLabel(self.frame_34)
        self.label_111.setMinimumSize(QtCore.QSize(0, 40))
        self.label_111.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_111.setFont(font)
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_34.addWidget(self.label_111)
        self.label_112 = QtWidgets.QLabel(self.frame_34)
        self.label_112.setMinimumSize(QtCore.QSize(0, 40))
        self.label_112.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_112.setFont(font)
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.verticalLayout_34.addWidget(self.label_112)
        self.gridLayout_4.addWidget(self.frame_34, 0, 0, 2, 1)
        self.frame_35 = QtWidgets.QFrame(self.groupBox_20)
        self.frame_35.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_35.setStyleSheet("background-color: transparent; border:0px;")
        self.frame_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dclient_name_5 = QtWidgets.QLineEdit(self.frame_35)
        self.dclient_name_5.setMinimumSize(QtCore.QSize(0, 40))
        self.dclient_name_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dclient_name_5.setFont(font)
        self.dclient_name_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dclient_name_5.setObjectName("dclient_name_5")
        self.verticalLayout_5.addWidget(self.dclient_name_5)
        self.catageory_5 = QtWidgets.QLineEdit(self.frame_35)
        self.catageory_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catageory_5.setFont(font)
        self.catageory_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.catageory_5.setObjectName("catageory_5")
        self.verticalLayout_5.addWidget(self.catageory_5)
        self.daddress_5 = QtWidgets.QLineEdit(self.frame_35)
        self.daddress_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.daddress_5.setFont(font)
        self.daddress_5.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.daddress_5.setText("")
        self.daddress_5.setObjectName("daddress_5")
        self.verticalLayout_5.addWidget(self.daddress_5)
        self.frame_18 = QtWidgets.QFrame(self.frame_35)
        self.frame_18.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.dd_dd_9 = QtWidgets.QLineEdit(self.frame_18)
        self.dd_dd_9.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_dd_9.setMaximumSize(QtCore.QSize(743, 1176))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_dd_9.setFont(font)
        self.dd_dd_9.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_dd_9.setObjectName("dd_dd_9")
        self.horizontalLayout_31.addWidget(self.dd_dd_9)
        self.dd_mm_9 = QtWidgets.QLineEdit(self.frame_18)
        self.dd_mm_9.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_mm_9.setMaximumSize(QtCore.QSize(919, 624))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_mm_9.setFont(font)
        self.dd_mm_9.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_mm_9.setObjectName("dd_mm_9")
        self.horizontalLayout_31.addWidget(self.dd_mm_9)
        self.dd_yy_9 = QtWidgets.QLineEdit(self.frame_18)
        self.dd_yy_9.setMinimumSize(QtCore.QSize(180, 40))
        self.dd_yy_9.setMaximumSize(QtCore.QSize(627, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_yy_9.setFont(font)
        self.dd_yy_9.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_yy_9.setObjectName("dd_yy_9")
        self.horizontalLayout_31.addWidget(self.dd_yy_9)
        self.verticalLayout_5.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_35)
        self.frame_19.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.dd_dd_10 = QtWidgets.QLineEdit(self.frame_19)
        self.dd_dd_10.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_dd_10.setMaximumSize(QtCore.QSize(743, 1176))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_dd_10.setFont(font)
        self.dd_dd_10.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_dd_10.setObjectName("dd_dd_10")
        self.horizontalLayout_32.addWidget(self.dd_dd_10)
        self.dd_mm_10 = QtWidgets.QLineEdit(self.frame_19)
        self.dd_mm_10.setMinimumSize(QtCore.QSize(0, 40))
        self.dd_mm_10.setMaximumSize(QtCore.QSize(919, 624))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_mm_10.setFont(font)
        self.dd_mm_10.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_mm_10.setObjectName("dd_mm_10")
        self.horizontalLayout_32.addWidget(self.dd_mm_10)
        self.dd_yy_10 = QtWidgets.QLineEdit(self.frame_19)
        self.dd_yy_10.setMinimumSize(QtCore.QSize(180, 40))
        self.dd_yy_10.setMaximumSize(QtCore.QSize(627, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dd_yy_10.setFont(font)
        self.dd_yy_10.setStyleSheet("QLineEdit{\n"
"border:1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}")
        self.dd_yy_10.setObjectName("dd_yy_10")
        self.horizontalLayout_32.addWidget(self.dd_yy_10)
        self.verticalLayout_5.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_35)
        self.frame_20.setMaximumSize(QtCore.QSize(350, 40))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_5.addWidget(self.frame_20)
        self.gridLayout_4.addWidget(self.frame_35, 0, 1, 2, 1)
        self.verticalLayout_6.addWidget(self.groupBox_20)
        self.frame_6 = QtWidgets.QFrame(self.designpage)
        self.frame_6.setStyleSheet("background-color:transparent; border:0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_5.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_6.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.designpage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_18.setTitle(_translate("Form", "Statement information Banking"))
        self.label_98.setText(_translate("Form", "Bank Name"))
        self.label_99.setText(_translate("Form", "Branch"))
        self.label_100.setText(_translate("Form", "Type"))
        self.label_101.setText(_translate("Form", "From"))
        self.label_102.setText(_translate("Form", "To"))
        self.dd_dd_5.setPlaceholderText(_translate("Form", "DD"))
        self.dd_mm_5.setPlaceholderText(_translate("Form", "MM"))
        self.dd_yy_5.setPlaceholderText(_translate("Form", "YYYY"))
        self.dd_dd_7.setPlaceholderText(_translate("Form", "DD"))
        self.dd_mm_7.setPlaceholderText(_translate("Form", "MM"))
        self.dd_yy_7.setPlaceholderText(_translate("Form", "YYYY"))
        self.pushButton.setText(_translate("Form", "Ok"))
        self.pushButton_2.setText(_translate("Form", "Cancle"))
        self.groupBox_20.setTitle(_translate("Form", "Statement information Designing"))
        self.label_108.setText(_translate("Form", "Catagorey"))
        self.label_109.setText(_translate("Form", "Client Name"))
        self.label_110.setText(_translate("Form", "Type"))
        self.label_111.setText(_translate("Form", "From"))
        self.label_112.setText(_translate("Form", "To"))
        self.dd_dd_9.setPlaceholderText(_translate("Form", "DD"))
        self.dd_mm_9.setPlaceholderText(_translate("Form", "MM"))
        self.dd_yy_9.setPlaceholderText(_translate("Form", "YYYY"))
        self.dd_dd_10.setPlaceholderText(_translate("Form", "DD"))
        self.dd_mm_10.setPlaceholderText(_translate("Form", "MM"))
        self.dd_yy_10.setPlaceholderText(_translate("Form", "YYYY"))
        self.pushButton_5.setText(_translate("Form", "Ok"))
        self.pushButton_6.setText(_translate("Form", "Cancle"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
