# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1106, 716)
        Form.setStyleSheet("    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
"\n"
"\n"
"border:2px solid grey;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background:transparent;\n"
"border:0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.export_2 = QtWidgets.QPushButton(self.frame)
        self.export_2.setMinimumSize(QtCore.QSize(70, 40))
        self.export_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_2.setFont(font)
        self.export_2.setStyleSheet("border:2px solid;\n"
"border-radius:9px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));")
        self.export_2.setObjectName("export_2")
        self.gridLayout.addWidget(self.export_2, 1, 3, 1, 1)
        self.bank_name_2 = QtWidgets.QComboBox(self.frame)
        self.bank_name_2.setMinimumSize(QtCore.QSize(400, 40))
        self.bank_name_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bank_name_2.setFont(font)
        self.bank_name_2.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.bank_name_2.setCurrentText("")
        self.bank_name_2.setObjectName("bank_name_2")
        self.gridLayout.addWidget(self.bank_name_2, 1, 0, 1, 1)
        self.design_se = QtWidgets.QComboBox(self.frame)
        self.design_se.setMinimumSize(QtCore.QSize(400, 40))
        self.design_se.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.design_se.setFont(font)
        self.design_se.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,                 stop:0 rgba(0, 96, 255, 255), stop:1 rgba(218, 255, 251, 255));\n"
"    image: url(:/newPrefix/dropdown.png);\n"
"    width: 50px;\n"
"}")
        self.design_se.setCurrentText("")
        self.design_se.setObjectName("design_se")
        self.gridLayout.addWidget(self.design_se, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"\n"
"QTabBar\n"
"{\n"
"    font: bold 12;\n"
"    border:0px;\n"
"    \n"
"    background-color: transparent;\n"
"    \n"
"}\n"
"\n"
" QTabBar::tab \n"
" {\n"
"\n"
"       background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1,       stop:0 rgba(0, 255, 240, 255), stop:1 rgba(161, 181, 255, 255));\n"
";\n"
"\n"
"    border-left: 1px solid #9B9B9B;\n"
"    border-right: 1px solid #9B9B9B;\n"
"    border-bottom: 1px solid #9B9B9B;\n"
"    border-top-color: #5A5A5A;\n"
"    min-width: 50ex;\n"
"    padding: 3px;\n"
" }S")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.export_2.setText(_translate("Form", "Export"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
